### ISSUE TITLE
Corrupt PCBDoc File?

### ISSUE THREAD

**Issue by GeorgeIoak** [harvie256/ESPTempMonitor#1]
I know this is a really old project but I was going to use up some old modules I found and thought I'd borrow your footprint and 3D model for the ESP-07. You have the name as ESPTempMonitor.CSPcbDoc and just renaming to ESPTempMonitorCS.PcbDoc would not stop the error when Altium tried to open the file.

I saw in your project file you had created libraries for this project so even those would work for me.

Thanks in advance,
George

**Comment by harvie256** [comment]
These are Altium Circuit Studio pcb files, not Altium Designer.

What are you trying to open them with?

**Comment by GeorgeIoak** [comment]
Oh sorry, I was using AD, sorry about that but thanks for following up.
